# Generated by Django 5.0.3 on 2024-04-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_batch_number_profile_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
