# Generated by Django 5.0.3 on 2024-04-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_photo', models.FileField(default=None, max_length=250, null=True, upload_to='team_img/')),
                ('trainer_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
    ]
