# Generated by Django 5.0.3 on 2024-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.FileField(default=None, max_length=250, null=True, upload_to='services_img/')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
            ],
        ),
    ]
