# Generated by Django 5.0.3 on 2024-04-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Campus Drive', 'Campus Drive'), ('Class Room', 'Class Room'), ('Lab', 'Lab'), ('Mock Interview', 'Mock Interview'), ('Placed Students', 'Placed Students')], max_length=100)),
                ('image', models.ImageField(upload_to='Gallery/')),
            ],
        ),
    ]
